### ISSUE TITLE
Merging set up branch fails Travis CI step. Not sure why! 

### ISSUE THREAD

**Issue by mackenziewillborn** [mackenziewillborn/TSH_Assignment#2]
Here is what the failure message looks like. 
<img width="1271" alt="screen shot 2019-02-13 at 10 04 42 pm" src="https://user-images.githubusercontent.com/43036326/52760013-f5d17900-2fdb-11e9-8e6d-b869655e13a5.png">

it says "The command "pytest -v --pep8" exited with 5."

**Comment by dward2** [comment]
The exit code of 5 means that no tests were run, which is the same message you see in the yellow line right above the exit code.  If I look at your setupbranch, there are not any test files on it.  So, that is why you get that exit code.  I can see that you seem to have other Travis Builds successfully running.
Any other questions on this topic?

**Comment by mackenziewillborn** [comment]
oh, awesome. thank you so much. and nope, I think that covers it!
